<?php

namespace App\Repository;

/**
 * HistoryDownloadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryDownloadRepository extends \Doctrine\ORM\EntityRepository
{
}
