<?php

namespace Application\Sonata\UserBundle\Admin;

use AppBundle\Admin\BaseAdminTrait;
use AppBundle\Entity\Position;
use Application\Sonata\UserBundle\Entity\Branch;
use Application\Sonata\UserBundle\Entity\User;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Form\Type\ChoiceFieldMaskType;
use Sonata\AdminBundle\Form\Type\ModelType;
use Sonata\CoreBundle\Form\Type\DatePickerType;
use Sonata\UserBundle\Admin\Entity\UserAdmin as BaseUserAdmin;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

class UserAdmin extends BaseUserAdmin
{
    use BaseAdminTrait;


    protected function configureListFields(ListMapper $listMapper)
    {
        parent::configureListFields($listMapper); // TODO: Change the autogenerated stub

        if(!empty($this->getConfigurationPool()->getContainer()->get('app.branch_option.repository')->findAll())) {
            $listMapper->add('branch', null, ['label' => 'Отделение',]);
        }
    }

    /**
     * {@inheritdoc}
     */
    protected function configureFormFields(FormMapper $formMapper)
    {
        $user = $this->getConfigurationPool()->getContainer()->get('security.token_storage')->getToken()->getUser();
        $isSuperAdmin = $this->getConfigurationPool()->getContainer()->get('security.authorization_checker')->isGranted('ROLE_SUPER_ADMIN');

        if (!$user instanceof User || (!$isSuperAdmin && $user != $this->getSubject())) {
            throw new AccessDeniedException();
        }

        if ($isSuperAdmin) {
            $formMapper
                ->tab('User');
        }

        $formMapper
            ->with('Profile', array('class' => 'col-md-6'))->end()
            ->with('General', array('class' => 'col-md-6'))->end();

        if ($isSuperAdmin) {
            $formMapper
                ->end();
        }

        if ($isSuperAdmin) {
            $formMapper
                ->tab('Security')
                ->with('Status', array('class' => 'col-md-4'))->end()
                ->with('Groups', array('class' => 'col-md-4'))->end()
                ->end();
        }

        if ($isSuperAdmin) {
            $formMapper
                ->tab('User');
        }
        $positions = [
            '' => 'Другая должность'
        ];
        foreach ($this->getConfigurationPool()->getContainer()->get('app.position_option.repository')->findAll() as $item) {
            $positions[$item->getId()] = $item->getName();
        }

        $branch = [];

        foreach ($this->getConfigurationPool()->getContainer()->get('app.branch_option.repository')->findAll() as $item) {
            $branch[$item->getId()] = $item->getName();
        }


        $formMapper
            ->with('General')
            ->add('username')
            ->add('email')
            ->add('plainPassword', TextType::class, array(
                'required' => (!$this->getSubject() || is_null($this->getSubject()->getId())),
            ));


        if(!empty($branch)) {


            $formMapper->add('branch', ChoiceFieldMaskType::class, array(
                'required' => true,
                'label' => 'Отделение',
                'choices' => $branch,
                'multiple' => false,
                'map' => [
                    '' => ['positionText']
                ],
            ));

        }

        $formMapper
            ->end()
            ->with('Profile')
            ->add('lastname', null, array('required' => false))
            ->add('firstname', null, array('required' => false))
            ->add('middlename', null, array('required' => false, 'label' => 'Отчество'))
            ->add('position', ChoiceFieldMaskType::class, array(
                'required' => false,
                'label' => 'Должность',
                'choices' => $positions,
                'multiple' => false,
                'map' => [
                    '' => ['positionText']
                ],
            ))
            ->add('positionText', TextType::class, [
                'required' => false,
                'label' => 'Другая должность',
            ])
            ->add('proxyDate', DatePickerType::class, array(
                'required' => false,
                'label' => 'Дата доверенности',
            ))
            ->add('proxyNum', null, array('required' => false, 'label' => 'Номер доверенности'))
            ->add('passport', TextareaType::class, array('required' => false, 'label' => 'Паспортные данные'))
            ->end();

        $transformer = $this
            ->getConfigurationPool()
            ->getContainer()->get('app.position_to_choice_field_mask_type.transformer');
        $formMapper->getFormBuilder()->get('position')->addModelTransformer($transformer);


        if(!empty($branch)) {
            $transformer = $this
                ->getConfigurationPool()
                ->getContainer()->get('app.branch_to_choice_field_mask_type.transformer');
            $formMapper->getFormBuilder()->get('branch')->addModelTransformer($transformer);

        }
        if ($isSuperAdmin) {
            $formMapper
                ->end();
        }

        if ($isSuperAdmin) {
            $formMapper
                ->tab('Security')
                ->with('Status')
                ->add('locked', null, array('required' => false))
                ->add('expired', null, array('required' => false))
                ->add('enabled', null, array('required' => false))
                ->add('credentialsExpired', null, array('required' => false))
                ->end()
                ->with('Groups')
                ->add('groups', ModelType::class, array(
                    'required' => false,
                    'expanded' => true,
                    'multiple' => true,
                ))
                ->end()
                ->end();
        }
    }

    /**
     * {@inheritdoc}
     */
    protected function configureDatagridFilters(DatagridMapper $filterMapper)
    {
        $filterMapper
            ->add('id', null, ['advanced_filter' => false])
            ->add('username', null, ['advanced_filter' => false])
            ->add('locked', null, ['advanced_filter' => false])
            ->add('email', null, ['advanced_filter' => false])
            ->add('groups', null, ['advanced_filter' => false]);
    }
}
