clients:
  - name: nochlezhka
    env_vars:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: $MYSQL_DATABASE
      DB_USER: $MYSQL_USER
      DB_PASSWORD: $MYSQL_PASSWORD
      ORG_NAME_SHORT: $ORG_NAME_SHORT
      ORG_NAME: $ORG_NAME
      ORG_DESCRIPTION: $ORG_DESCRIPTION
      ORG_DESCRIPTION_SHORT: $ORG_DESCRIPTION_SHORT
      ORG_CITY: $ORG_CITY
      ORG_CONTACTS_FULL: $ORG_CONTACTS_FULL
      DISPENSARY_NAME: $DISPENSARY_NAME
      DISPENSARY_ADDRESS: $DISPENSARY_ADDRESS
      DISPENSARY_PHONE: $DISPENSARY_PHONE
      EMPLOYMENT_NAME: $EMPLOYMENT_NAME
      EMPLOYMENT_ADDRESS: $EMPLOYMENT_ADDRESS
      EMPLOYMENT_INSPECTION: $EMPLOYMENT_INSPECTION
      SANITATION_NAME: $SANITATION_NAME
      SANITATION_ADDRESS: $SANITATION_ADDRESS
      SANITATION_TIME: $SANITATION_TIME