<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20220118190500 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE fos_user_user CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE branch_id branch_id INT DEFAULT NULL, CHANGE position_id position_id INT DEFAULT NULL, CHANGE last_login last_login DATETIME DEFAULT NULL, CHANGE expires_at expires_at DATETIME DEFAULT NULL, CHANGE confirmation_token confirmation_token VARCHAR(255) DEFAULT NULL, CHANGE password_requested_at password_requested_at DATETIME DEFAULT NULL, CHANGE credentials_expire_at credentials_expire_at DATETIME DEFAULT NULL, CHANGE date_of_birth date_of_birth DATETIME DEFAULT NULL, CHANGE firstname firstname VARCHAR(64) DEFAULT NULL, CHANGE lastname lastname VARCHAR(64) DEFAULT NULL, CHANGE website website VARCHAR(64) DEFAULT NULL, CHANGE biography biography VARCHAR(1000) DEFAULT NULL, CHANGE gender gender VARCHAR(1) DEFAULT NULL, CHANGE locale locale VARCHAR(8) DEFAULT NULL, CHANGE timezone timezone VARCHAR(64) DEFAULT NULL, CHANGE phone phone VARCHAR(64) DEFAULT NULL, CHANGE facebook_uid facebook_uid VARCHAR(255) DEFAULT NULL, CHANGE facebook_name facebook_name VARCHAR(255) DEFAULT NULL, CHANGE facebook_data facebook_data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE twitter_uid twitter_uid VARCHAR(255) DEFAULT NULL, CHANGE twitter_name twitter_name VARCHAR(255) DEFAULT NULL, CHANGE twitter_data twitter_data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE gplus_uid gplus_uid VARCHAR(255) DEFAULT NULL, CHANGE gplus_name gplus_name VARCHAR(255) DEFAULT NULL, CHANGE gplus_data gplus_data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE token token VARCHAR(255) DEFAULT NULL, CHANGE two_step_code two_step_code VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE middlename middlename VARCHAR(255) DEFAULT NULL, CHANGE proxy_date proxy_date DATE DEFAULT NULL, CHANGE proxy_num proxy_num VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE fos_user_group CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE code code VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE viewed_client CHANGE client_id client_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE position CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE branches CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE org_name_short org_name_short VARCHAR(255) DEFAULT NULL, CHANGE org_name org_name VARCHAR(255) DEFAULT NULL, CHANGE org_description org_description VARCHAR(255) DEFAULT NULL, CHANGE org_description_short org_description_short VARCHAR(255) DEFAULT NULL, CHANGE org_city org_city VARCHAR(255) DEFAULT NULL, CHANGE dispensary_name dispensary_name VARCHAR(255) DEFAULT NULL, CHANGE dispensary_address dispensary_address VARCHAR(255) DEFAULT NULL, CHANGE dispensary_phone dispensary_phone VARCHAR(255) DEFAULT NULL, CHANGE employment_name employment_name VARCHAR(255) DEFAULT NULL, CHANGE employment_address employment_address VARCHAR(255) DEFAULT NULL, CHANGE employment_inspection employment_inspection VARCHAR(255) DEFAULT NULL, CHANGE sanitation_name sanitation_name VARCHAR(255) DEFAULT NULL, CHANGE sanitation_address sanitation_address VARCHAR(255) DEFAULT NULL, CHANGE sanitation_time sanitation_time VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE notice CHANGE client_id client_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE date date DATE DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE contract_item CHANGE contract_id contract_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE date date DATE DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE date_start date_start DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE document_type CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE type type INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE client_field CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE code code VARCHAR(255) DEFAULT NULL, CHANGE enabled enabled TINYINT(1) DEFAULT NULL, CHANGE type type INT DEFAULT NULL, CHANGE required required TINYINT(1) DEFAULT NULL, CHANGE multiple multiple TINYINT(1) DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE mandatory_for_homeless mandatory_for_homeless TINYINT(1) DEFAULT NULL, CHANGE enabled_for_homeless enabled_for_homeless TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE document_file CHANGE client_id client_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE filename filename VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE client_form_field CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE flags flags LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:simple_array)\', CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE contract CHANGE client_id client_id INT DEFAULT NULL, CHANGE status_id status_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE document_id document_id INT DEFAULT NULL, CHANGE number number VARCHAR(255) DEFAULT NULL, CHANGE date_from date_from DATE DEFAULT NULL, CHANGE date_to date_to DATE DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE region CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE short_name short_name VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE delivery CHANGE delivery_item_id delivery_item_id INT DEFAULT NULL, CHANGE client_id client_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE client_field_value CHANGE client_id client_id INT DEFAULT NULL, CHANGE field_id field_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE option_id option_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE datetime datetime DATETIME DEFAULT NULL, CHANGE filename filename VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE generated_document_end_text CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE code code VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE client CHANGE last_registration_district_id last_registration_district_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE last_residence_district_id last_residence_district_id INT DEFAULT NULL, CHANGE photo_name photo_name VARCHAR(255) DEFAULT NULL, CHANGE birth_date birth_date DATE DEFAULT NULL, CHANGE birth_place birth_place VARCHAR(255) DEFAULT NULL, CHANGE gender gender INT DEFAULT NULL, CHANGE firstname firstname VARCHAR(255) DEFAULT NULL, CHANGE middlename middlename VARCHAR(255) DEFAULT NULL, CHANGE lastname lastname VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE is_homeless is_homeless TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE resident_questionnaire CHANGE client_id client_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE is_dwelling is_dwelling TINYINT(1) DEFAULT NULL, CHANGE room_type_id room_type_id INT DEFAULT NULL, CHANGE is_work is_work TINYINT(1) DEFAULT NULL, CHANGE is_work_official is_work_official TINYINT(1) DEFAULT NULL, CHANGE is_work_constant is_work_constant TINYINT(1) DEFAULT NULL, CHANGE changed_jobs_count_id changed_jobs_count_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE service_type CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE pay pay TINYINT(1) DEFAULT NULL, CHANGE document document TINYINT(1) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE generated_document_start_text CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE code code VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE shelter_room CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE number number VARCHAR(255) DEFAULT NULL, CHANGE max_occupants max_occupants INT DEFAULT NULL, CHANGE current_occupants current_occupants INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE generated_document CHANGE client_id client_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE start_text_id start_text_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE end_text_id end_text_id INT DEFAULT NULL, CHANGE number number VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE document CHANGE client_id client_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE address address VARCHAR(255) DEFAULT NULL, CHANGE city city VARCHAR(255) DEFAULT NULL, CHANGE date date DATE DEFAULT NULL, CHANGE number number VARCHAR(255) DEFAULT NULL, CHANGE number_prefix number_prefix VARCHAR(255) DEFAULT NULL, CHANGE registration registration INT DEFAULT NULL, CHANGE issued issued VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE generated_document_type CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE code code VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE contract_item_type CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE short_name short_name VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE delivery_item CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE history_download CHANGE client_id client_id INT DEFAULT NULL, CHANGE certificate_type_id certificate_type_id INT DEFAULT NULL, CHANGE user_id user_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE client_field_option CHANGE field_id field_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE not_single not_single TINYINT(1) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE district CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE region_id region_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE contract_status CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE certificate_type CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE downloadable downloadable TINYINT(1) DEFAULT NULL, CHANGE show_photo show_photo TINYINT(1) DEFAULT NULL, CHANGE show_date show_date TINYINT(1) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE shelter_history CHANGE client_id client_id INT DEFAULT NULL, CHANGE contract_id contract_id INT DEFAULT NULL, CHANGE room_id room_id INT DEFAULT NULL, CHANGE status_id status_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE diphtheria_vaccination_date diphtheria_vaccination_date DATE DEFAULT NULL, CHANGE fluorography_date fluorography_date DATE DEFAULT NULL, CHANGE hepatitis_vaccination_date hepatitis_vaccination_date DATE DEFAULT NULL, CHANGE typhus_vaccination_date typhus_vaccination_date DATE DEFAULT NULL, CHANGE date_from date_from DATE DEFAULT NULL, CHANGE date_to date_to DATE DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE contact_saved contact_saved SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE shelter_status CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE note CHANGE client_id client_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE important important TINYINT(1) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE client_form_response_value CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE history CHANGE client_id client_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE client_form_response CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE resident_questionnaire_id resident_questionnaire_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE client_form CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE certificate CHANGE client_id client_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE document_id document_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE city city VARCHAR(255) DEFAULT NULL, CHANGE number number VARCHAR(255) DEFAULT NULL, CHANGE date_from date_from DATE DEFAULT NULL, CHANGE date_to date_to DATE DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE menu_item CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE code code VARCHAR(255) DEFAULT NULL, CHANGE enabled enabled TINYINT(1) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE service CHANGE client_id client_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE amount amount INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE branches CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE org_name_short org_name_short VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE org_name org_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE org_description org_description VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE org_description_short org_description_short VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE org_city org_city VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE dispensary_name dispensary_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE dispensary_address dispensary_address VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE dispensary_phone dispensary_phone VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE employment_name employment_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE employment_address employment_address VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE employment_inspection employment_inspection VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE sanitation_name sanitation_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE sanitation_address sanitation_address VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE sanitation_time sanitation_time VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE certificate CHANGE client_id client_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE document_id document_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE city city VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE number number VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE date_from date_from DATE DEFAULT NULL, CHANGE date_to date_to DATE DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE certificate_type CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE downloadable downloadable TINYINT(1) DEFAULT NULL, CHANGE show_photo show_photo TINYINT(1) DEFAULT NULL, CHANGE show_date show_date TINYINT(1) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE client CHANGE last_residence_district_id last_residence_district_id INT DEFAULT NULL, CHANGE last_registration_district_id last_registration_district_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE photo_name photo_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE birth_date birth_date DATE DEFAULT NULL, CHANGE birth_place birth_place VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE gender gender INT DEFAULT NULL, CHANGE firstname firstname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE middlename middlename VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE lastname lastname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE is_homeless is_homeless TINYINT(1) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE client_field CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE code code VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE enabled enabled TINYINT(1) DEFAULT NULL, CHANGE enabled_for_homeless enabled_for_homeless TINYINT(1) DEFAULT NULL, CHANGE type type INT DEFAULT NULL, CHANGE required required TINYINT(1) DEFAULT NULL, CHANGE mandatory_for_homeless mandatory_for_homeless TINYINT(1) DEFAULT NULL, CHANGE multiple multiple TINYINT(1) DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE client_field_option CHANGE field_id field_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE not_single not_single TINYINT(1) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE client_field_value CHANGE field_id field_id INT DEFAULT NULL, CHANGE client_id client_id INT DEFAULT NULL, CHANGE option_id option_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE datetime datetime DATETIME DEFAULT NULL, CHANGE filename filename VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE client_form CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE client_form_field CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE flags flags LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:simple_array)\', CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE client_form_response CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE resident_questionnaire_id resident_questionnaire_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE client_form_response_value CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE contract CHANGE client_id client_id INT DEFAULT NULL, CHANGE status_id status_id INT DEFAULT NULL, CHANGE document_id document_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE number number VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE date_from date_from DATE DEFAULT NULL, CHANGE date_to date_to DATE DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE contract_item CHANGE contract_id contract_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE date_start date_start DATE DEFAULT NULL, CHANGE date date DATE DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE contract_item_type CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE short_name short_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE contract_status CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE delivery CHANGE client_id client_id INT DEFAULT NULL, CHANGE delivery_item_id delivery_item_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE delivery_item CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE district CHANGE region_id region_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE document CHANGE client_id client_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE address address VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE city city VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE date date DATE DEFAULT NULL, CHANGE number number VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE number_prefix number_prefix VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE registration registration INT DEFAULT NULL, CHANGE issued issued VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE document_file CHANGE client_id client_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE filename filename VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE document_type CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE type type INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE fos_user_group CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE code code VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE fos_user_user CHANGE position_id position_id INT DEFAULT NULL, CHANGE branch_id branch_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE last_login last_login DATETIME DEFAULT NULL, CHANGE expires_at expires_at DATETIME DEFAULT NULL, CHANGE confirmation_token confirmation_token VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE password_requested_at password_requested_at DATETIME DEFAULT NULL, CHANGE credentials_expire_at credentials_expire_at DATETIME DEFAULT NULL, CHANGE date_of_birth date_of_birth DATETIME DEFAULT NULL, CHANGE firstname firstname VARCHAR(64) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE lastname lastname VARCHAR(64) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE website website VARCHAR(64) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE biography biography VARCHAR(1000) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE gender gender VARCHAR(1) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE locale locale VARCHAR(8) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE timezone timezone VARCHAR(64) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE phone phone VARCHAR(64) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE facebook_uid facebook_uid VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE facebook_name facebook_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE facebook_data facebook_data LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json)\', CHANGE twitter_uid twitter_uid VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE twitter_name twitter_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE twitter_data twitter_data LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json)\', CHANGE gplus_uid gplus_uid VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE gplus_name gplus_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE gplus_data gplus_data LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json)\', CHANGE token token VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE two_step_code two_step_code VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE middlename middlename VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE proxy_date proxy_date DATE DEFAULT NULL, CHANGE proxy_num proxy_num VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE generated_document CHANGE client_id client_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE start_text_id start_text_id INT DEFAULT NULL, CHANGE end_text_id end_text_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE number number VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE generated_document_end_text CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE code code VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE generated_document_start_text CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE code code VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE generated_document_type CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE code code VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE history CHANGE client_id client_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE history_download CHANGE client_id client_id INT DEFAULT NULL, CHANGE user_id user_id INT DEFAULT NULL, CHANGE certificate_type_id certificate_type_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE menu_item CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE code code VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE enabled enabled TINYINT(1) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE note CHANGE client_id client_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE important important TINYINT(1) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE notice CHANGE client_id client_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE date date DATE DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE position CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE region CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE short_name short_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE resident_questionnaire CHANGE client_id client_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE is_dwelling is_dwelling TINYINT(1) DEFAULT NULL, CHANGE room_type_id room_type_id INT DEFAULT NULL, CHANGE is_work is_work TINYINT(1) DEFAULT NULL, CHANGE is_work_official is_work_official TINYINT(1) DEFAULT NULL, CHANGE is_work_constant is_work_constant TINYINT(1) DEFAULT NULL, CHANGE changed_jobs_count_id changed_jobs_count_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE service CHANGE client_id client_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE amount amount INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE service_type CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE pay pay TINYINT(1) DEFAULT NULL, CHANGE document document TINYINT(1) DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE shelter_history CHANGE room_id room_id INT DEFAULT NULL, CHANGE client_id client_id INT DEFAULT NULL, CHANGE status_id status_id INT DEFAULT NULL, CHANGE contract_id contract_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE diphtheria_vaccination_date diphtheria_vaccination_date DATE DEFAULT NULL, CHANGE fluorography_date fluorography_date DATE DEFAULT NULL, CHANGE hepatitis_vaccination_date hepatitis_vaccination_date DATE DEFAULT NULL, CHANGE typhus_vaccination_date typhus_vaccination_date DATE DEFAULT NULL, CHANGE contact_saved contact_saved TINYINT(1) DEFAULT \'0\', CHANGE date_from date_from DATE DEFAULT NULL, CHANGE date_to date_to DATE DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE shelter_room CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE number number VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE max_occupants max_occupants INT DEFAULT NULL, CHANGE current_occupants current_occupants INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE shelter_status CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE viewed_client CHANGE client_id client_id INT DEFAULT NULL, CHANGE created_by_id created_by_id INT DEFAULT NULL, CHANGE updated_by_id updated_by_id INT DEFAULT NULL, CHANGE sync_id sync_id INT DEFAULT NULL, CHANGE sort sort INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
    }
}
