<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20230413185611 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Set null for created_by_id and updated_by_id on user delete';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE certificate DROP FOREIGN KEY FK_219CDA4A896DBBDE');
        $this->addSql('ALTER TABLE certificate DROP FOREIGN KEY FK_219CDA4AB03A8386');
        $this->addSql('ALTER TABLE certificate ADD CONSTRAINT FK_219CDA4A896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE certificate ADD CONSTRAINT FK_219CDA4AB03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE certificate_type DROP FOREIGN KEY FK_F2C76A50896DBBDE');
        $this->addSql('ALTER TABLE certificate_type DROP FOREIGN KEY FK_F2C76A50B03A8386');
        $this->addSql('ALTER TABLE certificate_type ADD CONSTRAINT FK_F2C76A50896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE certificate_type ADD CONSTRAINT FK_F2C76A50B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455896DBBDE');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455B03A8386');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE client_field DROP FOREIGN KEY FK_F898D9EF896DBBDE');
        $this->addSql('ALTER TABLE client_field DROP FOREIGN KEY FK_F898D9EFB03A8386');
        $this->addSql('ALTER TABLE client_field ADD CONSTRAINT FK_F898D9EF896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE client_field ADD CONSTRAINT FK_F898D9EFB03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE client_field_option DROP FOREIGN KEY FK_C1C82EB3896DBBDE');
        $this->addSql('ALTER TABLE client_field_option DROP FOREIGN KEY FK_C1C82EB3B03A8386');
        $this->addSql('ALTER TABLE client_field_option ADD CONSTRAINT FK_C1C82EB3896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE client_field_option ADD CONSTRAINT FK_C1C82EB3B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE client_field_value DROP FOREIGN KEY FK_379BEBF4896DBBDE');
        $this->addSql('ALTER TABLE client_field_value DROP FOREIGN KEY FK_379BEBF4B03A8386');
        $this->addSql('ALTER TABLE client_field_value ADD CONSTRAINT FK_379BEBF4896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE client_field_value ADD CONSTRAINT FK_379BEBF4B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE client_form DROP FOREIGN KEY FK_83143E2D896DBBDE');
        $this->addSql('ALTER TABLE client_form DROP FOREIGN KEY FK_83143E2DB03A8386');
        $this->addSql('ALTER TABLE client_form ADD CONSTRAINT FK_83143E2D896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE client_form ADD CONSTRAINT FK_83143E2DB03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE client_form_field DROP FOREIGN KEY FK_48E6DCDA896DBBDE');
        $this->addSql('ALTER TABLE client_form_field DROP FOREIGN KEY FK_48E6DCDAB03A8386');
        $this->addSql('ALTER TABLE client_form_field ADD CONSTRAINT FK_48E6DCDA896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE client_form_field ADD CONSTRAINT FK_48E6DCDAB03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE client_form_response DROP FOREIGN KEY FK_F8F7B48B896DBBDE');
        $this->addSql('ALTER TABLE client_form_response DROP FOREIGN KEY FK_F8F7B48BB03A8386');
        $this->addSql('ALTER TABLE client_form_response ADD CONSTRAINT FK_F8F7B48B896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE client_form_response ADD CONSTRAINT FK_F8F7B48BB03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE client_form_response_value DROP FOREIGN KEY FK_A619F211896DBBDE');
        $this->addSql('ALTER TABLE client_form_response_value DROP FOREIGN KEY FK_A619F211B03A8386');
        $this->addSql('ALTER TABLE client_form_response_value ADD CONSTRAINT FK_A619F211896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE client_form_response_value ADD CONSTRAINT FK_A619F211B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE contract DROP FOREIGN KEY FK_E98F2859896DBBDE');
        $this->addSql('ALTER TABLE contract DROP FOREIGN KEY FK_E98F2859B03A8386');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT FK_E98F2859896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT FK_E98F2859B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE contract_item DROP FOREIGN KEY FK_776E6B76896DBBDE');
        $this->addSql('ALTER TABLE contract_item DROP FOREIGN KEY FK_776E6B76B03A8386');
        $this->addSql('ALTER TABLE contract_item ADD CONSTRAINT FK_776E6B76896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE contract_item ADD CONSTRAINT FK_776E6B76B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE contract_item_type DROP FOREIGN KEY FK_69794B44896DBBDE');
        $this->addSql('ALTER TABLE contract_item_type DROP FOREIGN KEY FK_69794B44B03A8386');
        $this->addSql('ALTER TABLE contract_item_type ADD CONSTRAINT FK_69794B44896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE contract_item_type ADD CONSTRAINT FK_69794B44B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE contract_status DROP FOREIGN KEY FK_47408051896DBBDE');
        $this->addSql('ALTER TABLE contract_status DROP FOREIGN KEY FK_47408051B03A8386');
        $this->addSql('ALTER TABLE contract_status ADD CONSTRAINT FK_47408051896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE contract_status ADD CONSTRAINT FK_47408051B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE district DROP FOREIGN KEY FK_31C15487896DBBDE');
        $this->addSql('ALTER TABLE district DROP FOREIGN KEY FK_31C15487B03A8386');
        $this->addSql('ALTER TABLE district ADD CONSTRAINT FK_31C15487896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE district ADD CONSTRAINT FK_31C15487B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A76896DBBDE');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A76B03A8386');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE document_file DROP FOREIGN KEY FK_2B2BBA83896DBBDE');
        $this->addSql('ALTER TABLE document_file DROP FOREIGN KEY FK_2B2BBA83B03A8386');
        $this->addSql('ALTER TABLE document_file ADD CONSTRAINT FK_2B2BBA83896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE document_file ADD CONSTRAINT FK_2B2BBA83B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE document_type DROP FOREIGN KEY FK_2B6ADBBA896DBBDE');
        $this->addSql('ALTER TABLE document_type DROP FOREIGN KEY FK_2B6ADBBAB03A8386');
        $this->addSql('ALTER TABLE document_type ADD CONSTRAINT FK_2B6ADBBA896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE document_type ADD CONSTRAINT FK_2B6ADBBAB03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE fos_user_user DROP FOREIGN KEY FK_C560D761896DBBDE');
        $this->addSql('ALTER TABLE fos_user_user DROP FOREIGN KEY FK_C560D761B03A8386');
        $this->addSql('ALTER TABLE fos_user_user ADD CONSTRAINT FK_C560D761896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE fos_user_user ADD CONSTRAINT FK_C560D761B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE generated_document DROP FOREIGN KEY FK_98C8BDCF896DBBDE');
        $this->addSql('ALTER TABLE generated_document DROP FOREIGN KEY FK_98C8BDCFB03A8386');
        $this->addSql('ALTER TABLE generated_document ADD CONSTRAINT FK_98C8BDCF896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE generated_document ADD CONSTRAINT FK_98C8BDCFB03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE generated_document_end_text DROP FOREIGN KEY FK_1FC324CE896DBBDE');
        $this->addSql('ALTER TABLE generated_document_end_text DROP FOREIGN KEY FK_1FC324CEB03A8386');
        $this->addSql('ALTER TABLE generated_document_end_text ADD CONSTRAINT FK_1FC324CE896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE generated_document_end_text ADD CONSTRAINT FK_1FC324CEB03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE generated_document_start_text DROP FOREIGN KEY FK_D15AEC56896DBBDE');
        $this->addSql('ALTER TABLE generated_document_start_text DROP FOREIGN KEY FK_D15AEC56B03A8386');
        $this->addSql('ALTER TABLE generated_document_start_text ADD CONSTRAINT FK_D15AEC56896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE generated_document_start_text ADD CONSTRAINT FK_D15AEC56B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE generated_document_type DROP FOREIGN KEY FK_73820995896DBBDE');
        $this->addSql('ALTER TABLE generated_document_type DROP FOREIGN KEY FK_73820995B03A8386');
        $this->addSql('ALTER TABLE generated_document_type ADD CONSTRAINT FK_73820995896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE generated_document_type ADD CONSTRAINT FK_73820995B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE history DROP FOREIGN KEY FK_27BA704B896DBBDE');
        $this->addSql('ALTER TABLE history DROP FOREIGN KEY FK_27BA704BB03A8386');
        $this->addSql('ALTER TABLE history ADD CONSTRAINT FK_27BA704B896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE history ADD CONSTRAINT FK_27BA704BB03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE menu_item DROP FOREIGN KEY FK_D754D550896DBBDE');
        $this->addSql('ALTER TABLE menu_item DROP FOREIGN KEY FK_D754D550B03A8386');
        $this->addSql('ALTER TABLE menu_item ADD CONSTRAINT FK_D754D550896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE menu_item ADD CONSTRAINT FK_D754D550B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE note DROP FOREIGN KEY FK_CFBDFA14896DBBDE');
        $this->addSql('ALTER TABLE note DROP FOREIGN KEY FK_CFBDFA14B03A8386');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE notice DROP FOREIGN KEY FK_480D45C2896DBBDE');
        $this->addSql('ALTER TABLE notice DROP FOREIGN KEY FK_480D45C2B03A8386');
        $this->addSql('ALTER TABLE notice ADD CONSTRAINT FK_480D45C2896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE notice ADD CONSTRAINT FK_480D45C2B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE position DROP FOREIGN KEY FK_462CE4F5896DBBDE');
        $this->addSql('ALTER TABLE position DROP FOREIGN KEY FK_462CE4F5B03A8386');
        $this->addSql('ALTER TABLE position ADD CONSTRAINT FK_462CE4F5896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE position ADD CONSTRAINT FK_462CE4F5B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE region DROP FOREIGN KEY FK_F62F176896DBBDE');
        $this->addSql('ALTER TABLE region DROP FOREIGN KEY FK_F62F176B03A8386');
        $this->addSql('ALTER TABLE region ADD CONSTRAINT FK_F62F176896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE region ADD CONSTRAINT FK_F62F176B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE service DROP FOREIGN KEY FK_E19D9AD2896DBBDE');
        $this->addSql('ALTER TABLE service DROP FOREIGN KEY FK_E19D9AD2B03A8386');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD2896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD2B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE service_type DROP FOREIGN KEY FK_429DE3C5896DBBDE');
        $this->addSql('ALTER TABLE service_type DROP FOREIGN KEY FK_429DE3C5B03A8386');
        $this->addSql('ALTER TABLE service_type ADD CONSTRAINT FK_429DE3C5896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE service_type ADD CONSTRAINT FK_429DE3C5B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE shelter_history DROP FOREIGN KEY FK_D04221A0896DBBDE');
        $this->addSql('ALTER TABLE shelter_history DROP FOREIGN KEY FK_D04221A0B03A8386');
        $this->addSql('ALTER TABLE shelter_history ADD CONSTRAINT FK_D04221A0896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE shelter_history ADD CONSTRAINT FK_D04221A0B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE shelter_room DROP FOREIGN KEY FK_1169D9ED896DBBDE');
        $this->addSql('ALTER TABLE shelter_room DROP FOREIGN KEY FK_1169D9EDB03A8386');
        $this->addSql('ALTER TABLE shelter_room ADD CONSTRAINT FK_1169D9ED896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE shelter_room ADD CONSTRAINT FK_1169D9EDB03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE shelter_status DROP FOREIGN KEY FK_E106D388896DBBDE');
        $this->addSql('ALTER TABLE shelter_status DROP FOREIGN KEY FK_E106D388B03A8386');
        $this->addSql('ALTER TABLE shelter_status ADD CONSTRAINT FK_E106D388896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE shelter_status ADD CONSTRAINT FK_E106D388B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE viewed_client DROP FOREIGN KEY FK_74C641DB896DBBDE');
        $this->addSql('ALTER TABLE viewed_client DROP FOREIGN KEY FK_74C641DBB03A8386');
        $this->addSql('ALTER TABLE viewed_client ADD CONSTRAINT FK_74C641DB896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE viewed_client ADD CONSTRAINT FK_74C641DBB03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE certificate DROP FOREIGN KEY FK_219CDA4AB03A8386');
        $this->addSql('ALTER TABLE certificate DROP FOREIGN KEY FK_219CDA4A896DBBDE');
        $this->addSql('ALTER TABLE certificate ADD CONSTRAINT FK_219CDA4AB03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE certificate ADD CONSTRAINT FK_219CDA4A896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE certificate_type DROP FOREIGN KEY FK_F2C76A50B03A8386');
        $this->addSql('ALTER TABLE certificate_type DROP FOREIGN KEY FK_F2C76A50896DBBDE');
        $this->addSql('ALTER TABLE certificate_type ADD CONSTRAINT FK_F2C76A50B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE certificate_type ADD CONSTRAINT FK_F2C76A50896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455B03A8386');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455896DBBDE');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE client_field DROP FOREIGN KEY FK_F898D9EFB03A8386');
        $this->addSql('ALTER TABLE client_field DROP FOREIGN KEY FK_F898D9EF896DBBDE');
        $this->addSql('ALTER TABLE client_field ADD CONSTRAINT FK_F898D9EFB03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE client_field ADD CONSTRAINT FK_F898D9EF896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE client_field_option DROP FOREIGN KEY FK_C1C82EB3B03A8386');
        $this->addSql('ALTER TABLE client_field_option DROP FOREIGN KEY FK_C1C82EB3896DBBDE');
        $this->addSql('ALTER TABLE client_field_option ADD CONSTRAINT FK_C1C82EB3B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE client_field_option ADD CONSTRAINT FK_C1C82EB3896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE client_field_value DROP FOREIGN KEY FK_379BEBF4B03A8386');
        $this->addSql('ALTER TABLE client_field_value DROP FOREIGN KEY FK_379BEBF4896DBBDE');
        $this->addSql('ALTER TABLE client_field_value ADD CONSTRAINT FK_379BEBF4B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE client_field_value ADD CONSTRAINT FK_379BEBF4896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE client_form DROP FOREIGN KEY FK_83143E2DB03A8386');
        $this->addSql('ALTER TABLE client_form DROP FOREIGN KEY FK_83143E2D896DBBDE');
        $this->addSql('ALTER TABLE client_form ADD CONSTRAINT FK_83143E2DB03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE client_form ADD CONSTRAINT FK_83143E2D896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE client_form_field DROP FOREIGN KEY FK_48E6DCDAB03A8386');
        $this->addSql('ALTER TABLE client_form_field DROP FOREIGN KEY FK_48E6DCDA896DBBDE');
        $this->addSql('ALTER TABLE client_form_field ADD CONSTRAINT FK_48E6DCDAB03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE client_form_field ADD CONSTRAINT FK_48E6DCDA896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE client_form_response DROP FOREIGN KEY FK_F8F7B48BB03A8386');
        $this->addSql('ALTER TABLE client_form_response DROP FOREIGN KEY FK_F8F7B48B896DBBDE');
        $this->addSql('ALTER TABLE client_form_response ADD CONSTRAINT FK_F8F7B48BB03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE client_form_response ADD CONSTRAINT FK_F8F7B48B896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE client_form_response_value DROP FOREIGN KEY FK_A619F211B03A8386');
        $this->addSql('ALTER TABLE client_form_response_value DROP FOREIGN KEY FK_A619F211896DBBDE');
        $this->addSql('ALTER TABLE client_form_response_value ADD CONSTRAINT FK_A619F211B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE client_form_response_value ADD CONSTRAINT FK_A619F211896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE contract DROP FOREIGN KEY FK_E98F2859B03A8386');
        $this->addSql('ALTER TABLE contract DROP FOREIGN KEY FK_E98F2859896DBBDE');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT FK_E98F2859B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT FK_E98F2859896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE contract_item DROP FOREIGN KEY FK_776E6B76B03A8386');
        $this->addSql('ALTER TABLE contract_item DROP FOREIGN KEY FK_776E6B76896DBBDE');
        $this->addSql('ALTER TABLE contract_item ADD CONSTRAINT FK_776E6B76B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE contract_item ADD CONSTRAINT FK_776E6B76896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE contract_item_type DROP FOREIGN KEY FK_69794B44B03A8386');
        $this->addSql('ALTER TABLE contract_item_type DROP FOREIGN KEY FK_69794B44896DBBDE');
        $this->addSql('ALTER TABLE contract_item_type ADD CONSTRAINT FK_69794B44B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE contract_item_type ADD CONSTRAINT FK_69794B44896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE contract_status DROP FOREIGN KEY FK_47408051B03A8386');
        $this->addSql('ALTER TABLE contract_status DROP FOREIGN KEY FK_47408051896DBBDE');
        $this->addSql('ALTER TABLE contract_status ADD CONSTRAINT FK_47408051B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE contract_status ADD CONSTRAINT FK_47408051896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE district DROP FOREIGN KEY FK_31C15487B03A8386');
        $this->addSql('ALTER TABLE district DROP FOREIGN KEY FK_31C15487896DBBDE');
        $this->addSql('ALTER TABLE district ADD CONSTRAINT FK_31C15487B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE district ADD CONSTRAINT FK_31C15487896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A76B03A8386');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A76896DBBDE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE document_file DROP FOREIGN KEY FK_2B2BBA83B03A8386');
        $this->addSql('ALTER TABLE document_file DROP FOREIGN KEY FK_2B2BBA83896DBBDE');
        $this->addSql('ALTER TABLE document_file ADD CONSTRAINT FK_2B2BBA83B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE document_file ADD CONSTRAINT FK_2B2BBA83896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE document_type DROP FOREIGN KEY FK_2B6ADBBAB03A8386');
        $this->addSql('ALTER TABLE document_type DROP FOREIGN KEY FK_2B6ADBBA896DBBDE');
        $this->addSql('ALTER TABLE document_type ADD CONSTRAINT FK_2B6ADBBAB03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE document_type ADD CONSTRAINT FK_2B6ADBBA896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE fos_user_user DROP FOREIGN KEY FK_C560D761B03A8386');
        $this->addSql('ALTER TABLE fos_user_user DROP FOREIGN KEY FK_C560D761896DBBDE');
        $this->addSql('ALTER TABLE fos_user_user ADD CONSTRAINT FK_C560D761B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE fos_user_user ADD CONSTRAINT FK_C560D761896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE generated_document DROP FOREIGN KEY FK_98C8BDCFB03A8386');
        $this->addSql('ALTER TABLE generated_document DROP FOREIGN KEY FK_98C8BDCF896DBBDE');
        $this->addSql('ALTER TABLE generated_document ADD CONSTRAINT FK_98C8BDCFB03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE generated_document ADD CONSTRAINT FK_98C8BDCF896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE generated_document_end_text DROP FOREIGN KEY FK_1FC324CEB03A8386');
        $this->addSql('ALTER TABLE generated_document_end_text DROP FOREIGN KEY FK_1FC324CE896DBBDE');
        $this->addSql('ALTER TABLE generated_document_end_text ADD CONSTRAINT FK_1FC324CEB03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE generated_document_end_text ADD CONSTRAINT FK_1FC324CE896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE generated_document_start_text DROP FOREIGN KEY FK_D15AEC56B03A8386');
        $this->addSql('ALTER TABLE generated_document_start_text DROP FOREIGN KEY FK_D15AEC56896DBBDE');
        $this->addSql('ALTER TABLE generated_document_start_text ADD CONSTRAINT FK_D15AEC56B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE generated_document_start_text ADD CONSTRAINT FK_D15AEC56896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE generated_document_type DROP FOREIGN KEY FK_73820995B03A8386');
        $this->addSql('ALTER TABLE generated_document_type DROP FOREIGN KEY FK_73820995896DBBDE');
        $this->addSql('ALTER TABLE generated_document_type ADD CONSTRAINT FK_73820995B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE generated_document_type ADD CONSTRAINT FK_73820995896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE history DROP FOREIGN KEY FK_27BA704BB03A8386');
        $this->addSql('ALTER TABLE history DROP FOREIGN KEY FK_27BA704B896DBBDE');
        $this->addSql('ALTER TABLE history ADD CONSTRAINT FK_27BA704BB03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE history ADD CONSTRAINT FK_27BA704B896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE menu_item DROP FOREIGN KEY FK_D754D550B03A8386');
        $this->addSql('ALTER TABLE menu_item DROP FOREIGN KEY FK_D754D550896DBBDE');
        $this->addSql('ALTER TABLE menu_item ADD CONSTRAINT FK_D754D550B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE menu_item ADD CONSTRAINT FK_D754D550896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE note DROP FOREIGN KEY FK_CFBDFA14B03A8386');
        $this->addSql('ALTER TABLE note DROP FOREIGN KEY FK_CFBDFA14896DBBDE');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE notice DROP FOREIGN KEY FK_480D45C2B03A8386');
        $this->addSql('ALTER TABLE notice DROP FOREIGN KEY FK_480D45C2896DBBDE');
        $this->addSql('ALTER TABLE notice ADD CONSTRAINT FK_480D45C2B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE notice ADD CONSTRAINT FK_480D45C2896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE position DROP FOREIGN KEY FK_462CE4F5B03A8386');
        $this->addSql('ALTER TABLE position DROP FOREIGN KEY FK_462CE4F5896DBBDE');
        $this->addSql('ALTER TABLE position ADD CONSTRAINT FK_462CE4F5B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE position ADD CONSTRAINT FK_462CE4F5896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE region DROP FOREIGN KEY FK_F62F176B03A8386');
        $this->addSql('ALTER TABLE region DROP FOREIGN KEY FK_F62F176896DBBDE');
        $this->addSql('ALTER TABLE region ADD CONSTRAINT FK_F62F176B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE region ADD CONSTRAINT FK_F62F176896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE service DROP FOREIGN KEY FK_E19D9AD2B03A8386');
        $this->addSql('ALTER TABLE service DROP FOREIGN KEY FK_E19D9AD2896DBBDE');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD2B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD2896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE service_type DROP FOREIGN KEY FK_429DE3C5B03A8386');
        $this->addSql('ALTER TABLE service_type DROP FOREIGN KEY FK_429DE3C5896DBBDE');
        $this->addSql('ALTER TABLE service_type ADD CONSTRAINT FK_429DE3C5B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE service_type ADD CONSTRAINT FK_429DE3C5896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE shelter_history DROP FOREIGN KEY FK_D04221A0B03A8386');
        $this->addSql('ALTER TABLE shelter_history DROP FOREIGN KEY FK_D04221A0896DBBDE');
        $this->addSql('ALTER TABLE shelter_history ADD CONSTRAINT FK_D04221A0B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE shelter_history ADD CONSTRAINT FK_D04221A0896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE shelter_room DROP FOREIGN KEY FK_1169D9EDB03A8386');
        $this->addSql('ALTER TABLE shelter_room DROP FOREIGN KEY FK_1169D9ED896DBBDE');
        $this->addSql('ALTER TABLE shelter_room ADD CONSTRAINT FK_1169D9EDB03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE shelter_room ADD CONSTRAINT FK_1169D9ED896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE shelter_status DROP FOREIGN KEY FK_E106D388B03A8386');
        $this->addSql('ALTER TABLE shelter_status DROP FOREIGN KEY FK_E106D388896DBBDE');
        $this->addSql('ALTER TABLE shelter_status ADD CONSTRAINT FK_E106D388B03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE shelter_status ADD CONSTRAINT FK_E106D388896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE viewed_client DROP FOREIGN KEY FK_74C641DB896DBBDE');
        $this->addSql('ALTER TABLE viewed_client DROP FOREIGN KEY FK_74C641DBB03A8386');
        $this->addSql('ALTER TABLE viewed_client ADD CONSTRAINT FK_74C641DB896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE viewed_client ADD CONSTRAINT FK_74C641DBB03A8386 FOREIGN KEY (created_by_id) REFERENCES fos_user_user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
    }
}
