app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin:
    resource: admin.yml

api_clients:
    type: rest
    prefix: api/v1
    resource: "@AppBundle/Controller/API/ClientsController.php"

api_delivery_items:
    type: rest
    prefix: api/v1
    resource: "@AppBundle/Controller/API/DeliveryItemsController.php"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

