<?php declare(strict_types=1);
// SPDX-License-Identifier: BSD-3-Clause

namespace App\Security\User;

class Role
{
    public const USER = 'ROLE_USER';
    public const ALLOWED_TO_SWITCH = 'ROLE_ALLOWED_TO_SWITCH';
    public const ADMIN = 'ROLE_ADMIN';
    public const SUPER_ADMIN = 'ROLE_SUPER_ADMIN';

    public const SONATA = 'SONATA';
    public const SONATA_ADMIN = 'ROLE_SONATA_ADMIN';

    public const SONATA_USER_ADMIN_USER_EDIT = 'ROLE_SONATA_USER_ADMIN_USER_EDIT';

    public const SONATA_PAGE_ADMIN_PAGE_EDIT = 'ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT';
    public const SONATA_PAGE_ADMIN_BLOCK_EDIT = 'ROLE_SONATA_PAGE_ADMIN_BLOCK_EDIT';

    public const APP_CLIENT_ADMIN_LIST = 'ROLE_APP\\ADMIN\\CLIENTADMIN_LIST';
    public const APP_CLIENT_ADMIN_CREATE = 'ROLE_APP\\ADMIN\\CLIENTADMIN_CREATE';
    public const APP_CLIENT_ADMIN_EDIT = 'ROLE_APP\\ADMIN\\CLIENTADMIN_EDIT';
    public const APP_CLIENT_ADMIN_ALL = 'ROLE_APP\\ADMIN\\CLIENTADMIN_ALL';

    public const APP_DOCUMENT_ADMIN_LIST = 'ROLE_APP\\ADMIN\\DOCUMENTADMIN_LIST';
    public const APP_DOCUMENT_ADMIN_ALL = 'ROLE_APP\\ADMIN\\DOCUMENTADMIN_ALL';
    public const APP_DOCUMENT_FILE_ADMIN_LIST = 'ROLE_APP\\ADMIN\\DOCUMENT_FILEADMIN_LIST';
    public const APP_DOCUMENT_FILE_ADMIN_ALL = 'ROLE_APP\\ADMIN\\DOCUMENT_FILEADMIN_ALL';

    public const APP_CONTRACT_ADMIN_LIST = 'ROLE_APP\\ADMIN\\CONTRACTADMIN_LIST';
    public const APP_CONTRACT_ADMIN_ALL = 'ROLE_APP\\ADMIN\\CONTRACTADMIN_ALL';

    public const APP_CERTIFICATE_ADMIN_LIST = 'ROLE_APP\\ADMIN\\CERTIFICATEADMIN_LIST';
    public const APP_CERTIFICATE_ADMIN_ALL = 'ROLE_APP\\ADMIN\\CERTIFICATEADMIN_ALL';

    public const APP_SHELTER_HISTORY_ADMIN_LIST = 'ROLE_APP\\ADMIN\\SHELTER_HISTORYADMIN_LIST';
    public const APP_SHELTER_HISTORY_ADMIN_ALL = 'ROLE_APP\\ADMIN\\SHELTER_HISTORYADMIN_ALL';

    public const APP_RESIDENT_QUESTIONNAIRE_ADMIN_LIST = 'ROLE_APP\\ADMIN\\RESIDENT_QUESTIONNAIREADMIN_LIST';
    public const APP_RESIDENT_QUESTIONNAIRE_ADMIN_ALL = 'ROLE_APP\\ADMIN\\RESIDENT_QUESTIONNAIREADMIN_ALL';

    public const APP_RESIDENT_FORM_RESPONSE_ADMIN_LIST = 'ROLE_APP\\ADMIN\\RESIDENT_FORM_RESPONSEADMIN_LIST';
    public const APP_RESIDENT_FORM_RESPONSE_ADMIN_ALL = 'ROLE_APP\\ADMIN\\RESIDENT_FORM_RESPONSEADMIN_ALL';

    public const APP_GENERATED_DOCUMENT_ADMIN_LIST = 'ROLE_APP\\ADMIN\\GENERATED_DOCUMENTADMIN_LIST';
    public const APP_GENERATED_DOCUMENT_ADMIN_ALL = 'ROLE_APP\\ADMIN\\GENERATED_DOCUMENTADMIN_ALL';

    public const APP_NOTE_ADMIN_LIST = 'ROLE_APP\\ADMIN\\NOTEADMIN_LIST';
    public const APP_NOTE_ADMIN_ALL = 'ROLE_APP\\ADMIN\\NOTEADMIN_ALL';

    public const APP_NOTICE_ADMIN_LIST = 'ROLE_APP\\ADMIN\\NOTICEADMIN_LIST';
    public const APP_NOTICE_ADMIN_ALL = 'ROLE_APP\\ADMIN\\NOTICEADMIN_ALL';

    public const APP_SERVICE_ADMIN_LIST = 'ROLE_APP\\ADMIN\\SERVICEADMIN_LIST';
    public const APP_SERVICE_ADMIN_ALL = 'ROLE_APP\\ADMIN\\SERVICEADMIN_ALL';
}
