<?php
// SPDX-License-Identifier: BSD-3-Clause

declare(strict_types=1);

namespace App\Security\User;

class Role
{
    public const EMPLOYEE = 'ROLE_EMPLOYEE';
    public const ALLOWED_TO_SWITCH = 'ROLE_ALLOWED_TO_SWITCH';

    public const SONATA_ADMIN = 'ROLE_SONATA_ADMIN';
    public const SUPER_ADMIN = 'ROLE_SUPER_ADMIN';

    public const SONATA_USER_ADMIN_USER_EDIT = 'ROLE_SONATA_USER_ADMIN_USER_EDIT';

    public const APP_CLIENT_ADMIN_ALL = 'ROLE_APP_CLIENT_ADMIN_ALL';
    public const APP_DOCUMENT_ADMIN_ALL = 'ROLE_APP_DOCUMENT_ADMIN_ALL';
    public const APP_DOCUMENT_FILE_ADMIN_ALL = 'ROLE_APP_DOCUMENT_FILE_ADMIN_ALL';
    public const APP_CONTRACT_ADMIN_ALL = 'ROLE_APP_CONTRACT_ADMIN_ALL';
    public const APP_CERTIFICATE_ADMIN_ALL = 'ROLE_APP_CERTIFICATE_ADMIN_ALL';
    public const APP_SHELTER_HISTORY_ADMIN_ALL = 'ROLE_APP_SHELTER_HISTORY_ADMIN_ALL';
    public const APP_RESIDENT_QUESTIONNAIRE_ADMIN_ALL = 'ROLE_APP_RESIDENT_QUESTIONNAIRE_ADMIN_ALL';
    public const APP_RESIDENT_FORM_RESPONSE_ADMIN_ALL = 'ROLE_APP_RESIDENT_FORM_RESPONSE_ADMIN_ALL';
    public const APP_GENERATED_DOCUMENT_ADMIN_ALL = 'ROLE_APP_GENERATED_DOCUMENT_ADMIN_ALL';
    public const APP_NOTE_ADMIN_ALL = 'ROLE_APP_NOTE_ADMIN_ALL';
    public const APP_NOTICE_ADMIN_ALL = 'ROLE_APP_NOTICE_ADMIN_ALL';
    public const APP_SERVICE_ADMIN_ALL = 'ROLE_APP_SERVICE_ADMIN_ALL';
}
